"""initial create

Revision ID: 385e26107091
Revises: 
Create Date: 2024-02-20 12:40:30.182064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385e26107091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist_table',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Artist_table_id'), 'Artist_table', ['id'], unique=False)
    op.create_table('Playlist_table',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Playlist_table_id'), 'Playlist_table', ['id'], unique=False)
    op.create_table('Song_table',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Song_table_id'), 'Song_table', ['id'], unique=False)
    op.create_table('Playlist_Song_table',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['Playlist_table.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song_table.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Playlist_Song_table')
    op.drop_index(op.f('ix_Song_table_id'), table_name='Song_table')
    op.drop_table('Song_table')
    op.drop_index(op.f('ix_Playlist_table_id'), table_name='Playlist_table')
    op.drop_table('Playlist_table')
    op.drop_index(op.f('ix_Artist_table_id'), table_name='Artist_table')
    op.drop_table('Artist_table')
    # ### end Alembic commands ###
